application: nakul-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: play.app

- url: /static
  static_dir: static

libraries:
 - name: jinja2
   version: latest
